### ISSUE TITLE
Call Back Function throws Ambiguous match found error in Unity

### ISSUE THREAD

**Issue by akash1306** [lafith/ROSBridgeLib#1]
**Describe the bug**
The callback function in the subscriber script of the readme files throws an Ambiguous match found error when called in a scene. This results in no subscription of topics in Unity. 

**To Reproduce**
Use the scripts mentioned in the ReadMe file and use them in a barebones scene. 

**Desktop :**
 - Windows
 - Unity Version 2020.1.6 and 2019.4.3

**Comment by lafith** [comment]
Fixed it.
Error was in passing  message into CallBack Function.
